### ISSUE TITLE
無法 createAdmin

### ISSUE THREAD

**Issue by derekchung** [lan894734188/ss-panel-ssr#1]
看了一下 
在createAdmin 時出現Error 說 user 的 ga_token 不可以是 NULL

**Comment by lan894734188** [comment]
嗯 bug已修好 请更新代码

**Comment by derekchung** [comment]
Uncaught Error: Class 'App\Command\GA' not found

XCat.php 少了一句 use App\Utils\GA; 吧
加上後就可以了

**Comment by lan894734188** [comment]
啊 忘记加了… 已fix
