### ISSUE TITLE
能否添加用户配置二维码？

### ISSUE THREAD

**Issue by shom** [lan894734188/ss-panel-ssr#11]
RT

**Comment by lan894734188** [comment]
在节点的详细信息里有的

**Comment by PYGC** [comment]
没有找到。。

**Comment by lan894734188** [comment]
@PYGC

**Comment by lan894734188** [comment]
[http://wx4.sinaimg.cn/mw690/6ca8764dgy1fgcf7icbmwj20af0do0t8.jpg]
[http://wx1.sinaimg.cn/mw690/6ca8764dgy1fgcf7k3xsfj20cl0bs0tc.jpg]

**Comment by PYGC** [comment]
[http://wx3.sinaimg.cn/large/68740a71gy1fgcff4bbvzj20mr0pgmy2.jpg]
是不是我用LAMP的原因。。
