### ISSUE TITLE
用户编辑界面有误？

### ISSUE THREAD

**Issue by yinws** [lan894734188/ss-panel-ssr#15]
https://wx3.sinaimg.cn/large/629e6ec6gy1ffnby4x9bbj217w0gkjt5.jpg
刚安装，是2017.5.16最新版，用户编辑界面排版好像有错误，修改保存不生效，点击修改并没有反应，开启debug模式也没反应。

**Comment by lan894734188** [comment]
我测试了一下似乎并没有问题呢
建议看看php日志

**Comment by lan894734188** [comment]
我看了一下是外部css js丢失的问题 你可以检查一下你的nginx

**Comment by yinws** [comment]
谢谢，我去看看，其他页面正常，就是节点管理和用户管理页面有问题，应该是js问题

**Comment by lan894734188** [comment]
建议 git pull 拉取一下分支

**Comment by yinws** [comment]
nginx我就加了public路径和一个重定向，linux上的网页不是很熟也不知道怎么搞了
git  pull是最新版的...

**Comment by lan894734188** [comment]
Mvc的伪静态加了是吧？

2017年5月16日 20:18 於 "yinws" <notifications@github.com> 寫道：

**Comment by yinws** [comment]
location / { 
try_files $uri $uri/ /index.php$is_args$args;
}
这个嘛？添加了

**Comment by lan894734188** [comment]
浏览器F12看看缺了什么文件

2017年5月16日 20:48 於 "yinws" <notifications@github.com> 寫道：

location / {
try_files $uri $uri/ /index.php$is_args$args;
}
这个嘛？添加了

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/lan894734188/ss-panel-ssr/issues/15#issuecomment-301771451>,
or mute the thread

**Comment by yinws** [comment]
https://ws4.sinaimg.cn/large/629e6ec6gy1ffnidomaghj20gi087gmw.jpg
https://ws3.sinaimg.cn/large/629e6ec6gy1ffnie1acl2j20ga04uq3i.jpg
上部分的css和js路径和下面不一样，那个assets文件夹

**Comment by lan894734188** [comment]
Network里面有哪些加载失败的

2017年5月16日 21:11 於 "yinws" <notifications@github.com> 寫道：

**Comment by yinws** [comment]
https://wx3.sinaimg.cn/large/629e6ec6gy1ffnjqvkzivj20py0dvdhh.jpg

**Comment by lan894734188** [comment]
点其中一个404的看看请求连接

2017年5月16日 21:57 於 "yinws" <notifications@github.com> 寫道：

**Comment by yinws** [comment]
https://ws1.sinaimg.cn/large/629e6ec6gy1ffnjz4gdmij20q60g8wgm.jpg
https://ws2.sinaimg.cn/large/629e6ec6gy1ffnjynhcvmj20q50gbgom.jpg

**Comment by lan894734188** [comment]
bug已修好 请拉取最新分支

**Comment by yinws** [comment]
https://ws1.sinaimg.cn/large/629e6ec6gy1ffnltnphexj20xs0f5acq.jpg
重启vps，换无缓存的浏览器试过。
这次更奇葩，网上各种图标都显示不出来了。

**Comment by yinws** [comment]
图标好像是本地网络的问题，但是界面还是那样，是我的特例吗？
批发靓鸡仔 <notifications@github.com>于2017年5月16日 周二22:42写道：

**Comment by lan894734188** [comment]
啧啧我也觉得奇怪

2017年5月16日 23:26 於 "yinws" <notifications@github.com> 寫道：

**Comment by yinws** [comment]
暂时放弃了，直接改数据库……等下次git pull，闲一点再装台vps试试
批发靓鸡仔 <notifications@github.com>于2017年5月16日 周二23:35写道：

**Comment by yinws** [comment]
不好意思，是昨天git pull出了点问题，问题已解决！感谢
