### ISSUE TITLE
ShadowsocksR Subscription Support

### ISSUE THREAD

**Issue by Indexyz** [lan894734188/ss-panel-ssr#16]
ShadowsocksR Client is supposed server subscription now.
Cloud you add support for it?

The API document: [link](https://github.com/breakwa11/shadowsocks-rss/wiki/Subscribe-%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AE%A2%E9%98%85%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3)

**Comment by lan894734188** [comment]
I am waiting for it to be popular
