### ISSUE TITLE
生成公共邀请码后进入公共邀请码页面返回Page Not Found

### ISSUE THREAD

**Issue by Nchyn** [lan894734188/ss-panel-ssr#17]
如题，实在google不出来解决办法故前来咨询

Page Not Found
The page you are looking for could not be found. Check the address bar to ensure your URL is spelled correctly. If all else fails, you can visit our home page at the link below.

Visit the Home Page

**Comment by lan894734188** [comment]
已推更新修复

**Comment by lan894734188** [comment]
邀请码是放在主页的 如果还是没有请检查.env邀请码是否显示
