### ISSUE TITLE
无法显示节点列表

### ISSUE THREAD

**Issue by JeremyPeng** [lan894734188/ss-panel-ssr#22]
配置后，使用正常，公告正常。
唯一问题就是无法显示节点列表...展开后是空的，但是没有任何的显示。
是有什么规则需要设置吗？

![image](https://user-images.githubusercontent.com/4402112/28501293-7e27c7a6-700b-11e7-801a-ca2964c100a9.png)

![image](https://user-images.githubusercontent.com/4402112/28501286-53dc7672-700b-11e7-976d-2a09164760a0.png)

**Comment by lan894734188** [comment]
@JeremyPeng 节点群组级别不可空

**Comment by lan894734188** [comment]
@JeremyPeng 群组级别与账户群组级别对于

**Comment by JeremyPeng** [comment]
非常感谢，圆满解决:D
