### ISSUE TITLE
Slim Application Error A website error has occurred. Sorry for the temporary inconvenience.

### ISSUE THREAD

**Issue by hemla** [lan894734188/ss-panel-ssr#5]
换了三个lnmp环境，都是同样的错误
Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.
在原版我遇到过是因为storage没给权限，但是这个给了也还是这样。
检查redis Composer也正常。
请问还漏下什么吗？谢谢

**Comment by lan894734188** [comment]
请检查一下php日志呢

**Comment by hemla** [comment]
开debug页面显示如图
![snipaste20170111_183728](https://cloud.githubusercontent.com/assets/18051159/21845315/1a33368e-d82d-11e6-84f6-6f272f2f9b88.jpg)

**Comment by lan894734188** [comment]
啧啧 遗留了个大bug 你git pull 拉取一下新代码就好了
或手动将.env里的条目修改如下
theme    = 'md_interface'   // 主题
